# Site settings
# =============
title: "kg's log." 
tagline: What even is a tagline? 
email: wendirful@gmail.com 
description: "Yes? No?" 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://x-axis.github.io" # the base hostname & protocol for your site

author:
  name: Keenan Gao 
  email: wendirful@gmail.com
  url: http://x-axis.github.io/about.html

github:
  repo: https://github.com/x-axis/x-axis.github.io

twitter:
  username: keenangao

google_analytics: UA-79509497-1

# Build settings
# ==============
source: ./
destination: ../x-axis.github.io/

markdown: kramdown
highlighter: rouge

exclude: [README.md, LICENSE.md]
permalink: none
timezone: America/Chicago
