# Site settings
# =============
title: "Heiswayi Nrird on Tech"
tagline: Another Software Guy's Blog
email: hnrird@gmail.com
description: "1+1=3 is always TRUE in my world, a balance between binary and reality."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

author:
  name: Heiswayi Nrird
  email: hnrird@gmail.com
  url: http://heiswayi.github.io/about.html

github:
  repo: https://github.com/heiswayi/heiswayi.github.io

twitter:
  username: HeiswayiNrird

google_analytics: UA-58296043-7

# Build settings
# ==============
source: ./
destination: ../heiswayi.github.io/

markdown: kramdown
highlighter: rouge

exclude: [README.md, LICENSE.md]
permalink: none
timezone: Asia/Kuala_Lumpur
