# Site settings
# =============
title: "keenan's log." 
tagline: What even is a tagline? 
email:  
description: "Yes? No?" 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

author:
  name: Keenan Gao 
  email: gaoxx867@umn.edu 
  url: http://x-axis.github.io/about.html

github:
  repo: https://github.com/x-axis/x-axis.github.io

twitter:
  username: keenangao

google_analytics: UA-79509497-1

# Build settings
# ==============
source: ./
destination: ../x-axis.github.io/

markdown: kramdown
highlighter: rouge

exclude: [README.md, LICENSE.md, Gemfile, Gemfile.lock]
permalink: none
timezone: America/Chicago

gems:
  - jekyll-assets

assets:
  autowrite: true
  prefix: "/images"
  digest: true
  assets:
    - "*.png"
 
  dirname: images
  baseurl: /images/
  sources:
    - _images/


